num_workers: 1

data:
  data_dir: ''
  dataset_name: "voc"   # coco, imagenet100k, imagenet or voc
  num_classes: 21
  size_crops: 448

val:
  arch: 'vit_small'
  batch_size: 1
  seed: 3407
  patch_size: 16
  embed_dim: 384
  hidden_dim: 768
  num_decode_layers: 1
  decoder_num_heads: 3
  num_queries: 5  # effective queries for mask generation, always ends with an 'Others' query
  last_self_attention: False   # whether use attention map as foreground hint
  mask_eval_size: 100
  checkpoint: './epoch10.pth'
